version: '3.8'

networks:
  monitoring:
    driver: bridge
    
volumes:
  prometheus_data: {}

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    #ports:
      #- "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - /var/grafana-data:/prometheus
    command:
      - '--web.config.file=/etc/prometheus/web.yml'
      - '--config.file=/etc/prometheus/prometheus.yml'
      #- '--storage.tsdb.path=/prometheus'
      #- '--web.console.libraries=/etc/prometheus/console_libraries'
      #- '--web.console.templates=/etc/prometheus/consoles'
      #- '--web.enable-lifecycle'
    expose:
      - 9090
    networks:
      - monitoring

  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: blackbox
    privileged: true
    volumes:
      - ./blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml
    ports:
      - '9115:9115'
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:8.2.7
    container_name: grafana
    volumes:
            - ./grafana/grafana.ini:/etc/grafana/grafana.ini
            - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
            - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yaml
            - ./dashboards:/etc/grafana/dashboards
    ports:
      - 3000:3000
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:v0.12.0
    container_name: alertmanager
    ports:
      - 9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'
    networks:
      - monitoring

  script_exporter:
    command:
      - '-config.file=/bin/examples/config.yaml'
      - '-web.listen-address=:9469'
    container_name: 'script-exporter'
    image: 'ricoberger/script_exporter:v2.4.0'
    volumes:
      - ./scripts:/bin/examples
    networks:
      - monitoring
